### ISSUE TITLE
Remove truncation of the body of bounced messages.

### ISSUE THREAD

**Issue by aleksandr-hramcov** [tonlabs/ever-node#140]
Problem:
Currently the body of bounced messages is truncated to 256 bits. In this case, the first 32 bits store the functionId.
This leads to the fact that it is impossible in the onBounce function to get sufficient information about the failed call.

When developing smart contracts, you have to save all the temporary necessary parameters in a mapping with the uint64 nonce key, make the first argument of the called function uint64 nonce, and then send another additional callback if successful for cleaning.
This approach cannot always be used and is not without drawbacks, as it can lead to an uncontrolled growth of temporary data and additional bugs.

Offer:
Do not truncate the body of bounced message and send all original data.

**Comment by 30mb1** [comment]
Must have feature, will simplify contracts logic much

**Comment by Futurizt** [comment]
WIP

**Comment by abionics** [comment]
Waiting for this feature for a long time!

**Comment by cassandrus** [comment]
It was proposed long ago - https://forum.freeton.org/t/tip-8-bounce-message-size/10866

**Comment by NoamDev** [comment]
i believe this will be very useful and wil finally allow real error handling.

**Comment by mnill** [comment]
Why this was not solved already? :-)

**Comment by SkySonR** [comment]
Убрать костыль или не убрать? Дайте-ка подумать...

**Comment by SkySonR** [comment]
can be closed?

**Comment by bvscd** [comment]
Already done
