### ISSUE TITLE
How to resolve this error

### ISSUE THREAD

**Issue by chen499** [tonlabs/ever-node#186]
1700213031.273338034 WARN [ton_node::network::neighbours] 139696071001856: Capabilities were not received from MXfG/zYVL747/eND1E3Lkj8H3tyJ403pYtdurK+MbBE= Wazq6hhjvNjq68AlHctgXrCHMLlLCdgj+Y23DklOpNc= src/network/neighbours.rs:658
1700213031.656882459 WARN [ton_node::network::neighbours] 139696054191872: Capabilities were not received from GcdMHKDvDH5gT/VQhiDbU1IKc5V4IOe1QqcegU74g5A= Wazq6hhjvNjq68AlHctgXrCHMLlLCdgj+Y23DklOpNc= src/network/neighbours.rs:658
1700213031.940775284 WARN [boot] 139696106994688: check_proof error: Invalid TL-B constructor tag `#9bc7a988` while parsing `BlockInfo` struct
1700213032.356568315 WARN [ton_node::network::neighbours] 139696012166912: Capabilities were not received from VqtVjgjdfGDb1lNNWPudEBWU4kF9mcGn87bbWDEhwtc= Wazq6hhjvNjq68AlHctgXrCHMLlLCdgj+Y23DklOpNc= src/network/neighbours.rs:658
1700213033.568022240 WARN [ton_node::network::neighbours] 139695911307008: Capabilities were not received from 7JIjPZlQdoMnfV9hhz0ZJwrgQT/MZlMc4JLQSdeXC1Y= Wazq6hhjvNjq68AlHctgXrCHMLlLCdgj+Y23DklOpNc= src/network/neighbours.rs:658
1700213033.569782727 WARN [boot] 139696106994688: check_proof error: Invalid TL-B constructor tag `#9bc7a988` while parsing `BlockInfo` struct
1700213033.671034278 WARN [ton_node::network::neighbours] 139696012166912: Capabilities were not received from uQi5WIaPvQbwb+9Dhwv0885G+oeF7q8IYWta3Q2Fju0= Wazq6hhjvNjq68AlHctgXrCHMLlLCdgj+Y23DklOpNc= src/network/neighbours.rs:658
1700213033.838116622 WARN [ton_node::network::neighbours] 139695978546944: Capabilities were not received from 4v/qCPbLRA9MwALrwdShYhrc7RrY0fALuWvVMY8oB3Y= Wazq6hhjvNjq68AlHctgXrCHMLlLCdgj+Y23DklOpNc= src/network/neighbours.rs:658
1700213033.863737271 WARN [ton_node::network::neighbours] 139696045786880: Capabilities were not received from cUEyOXwkokzSEYOh0QvmYgOmMc4Zd/OLHA3SpeesG2M= Wazq6hhjvNjq68AlHctgXrCHMLlLCdgj+Y23DklOpNc= src/network/neighbours.rs:658
1700213035.194965273 WARN [boot] 139696106994688: check_proof error: Invalid TL-B constructor tag `#9bc7a988` while parsing `BlockInfo` struct
1700213036.285296230 WARN [ton_node::network::neighbours] 139696045786880: Capabilities were not received from xfQypu84m69cC9/gUT7jfP/XHqXKl2FNGsghAjZKUVc= Wazq6hhjvNjq68AlHctgXrCHMLlLCdgj+Y23DklOpNc= src/network/neighbours.rs:658
1700213036.335415524 INFO [telemetry] 139696012166912:

**Comment by bvscd** [comment]
Issue with invalid TL-B constructor tag was fixed.   
"Capabilities were not received" message is not critical, it happens when testing access to neighbours, and some neighbours are dead
